### ISSUE TITLE
Colab?

### ISSUE THREAD

**Issue by Devetec** [CompVis/geometry-free-view-synthesis#2]
Is this possible to run in colab with the demo? Infinite Nature was able to create a demo in Colab :)

**Comment by pesser** [comment]
Great idea, I quickly [threw something together](https://colab.research.google.com/github/CompVis/geometry-free-view-synthesis/blob/master/scripts/braindance.ipynb). But the javascript<->python communication is a bit slow so the experience is not quite as nice compared to running it locally ;)

**Comment by Devetec** [comment]
Thanks!
