### ISSUE TITLE
OSError: Cannot open resource on ImageFont

### ISSUE THREAD

**Issue by chris-aeviator** [CompVis/geometry-free-view-synthesis#3]
I've used the "alternative" install method. I'm running into this when hitting `SPACE` in the scene.

![image](https://user-images.githubusercontent.com/11522213/115844974-ae976c00-a420-11eb-8185-13309645a4f8.png)

**Comment by chris-aeviator** [comment]
I'm able to get around this by installing the `fonts-liberation` package via `apt`, anyhow, this should be included in the standard installation script of the package.

**Comment by pesser** [comment]
Thanks for letting us know. It now falls back to a default font.
