### ISSUE TITLE
[Question] Multiple Image Input

### ISSUE THREAD

**Issue by chris-aeviator** [CompVis/geometry-free-view-synthesis#4]
How can I include multiple input images into the synth? When starting `braindance.py path-to-my-imagefolder`, a filemanager opens that just let's me select a single image.

I'd like to re-create a whole room by including the info's of multiple images.

**Comment by pesser** [comment]
This work specifically focused on the synthesis of novel views from a single input image. Currently it cannot take into account multiple images, but that's a very interesting direction for future works!

If you have many views available, you might be interested in [Stable View Synthesis](https://github.com/intel-isl/StableViewSynthesis).
