### ISSUE TITLE
downloading RealEstate10K

### ISSUE THREAD

**Issue by avihu111** [CompVis/geometry-free-view-synthesis#7]
Hi, I downloaded the RealEstate10K dataset, and it only contains the txt files.
Can you attach your code for downloading the dataset from those txt files?
Thanks!

**Comment by pesser** [comment]
Hi,
I'm sorry but I don't think that we are allowed to share that code. However, maybe someone else wrote a "RealEstate10K_Downloader" ;)
Best
Patrick

**Comment by avihu111** [comment]
Found it. Thanks!
posting for others that might be interested
https://github.com/cashiwamochi/RealEstate10K_Downloader

**Comment by zimingzhong** [comment]
Hi, @avihu111 
I am a researcher in China. It is hard for me to download videos from Youtube in server, which already wastes me weeks to figure out. Could you share the dataset with me and I can download it from my laptop which can access any website. I promise I will use it followed academic license. Thank you.

**Comment by zifeiyuu** [comment]
> Hi, @avihu111 I am a researcher in China. It is hard for me to download videos from Youtube in server, which already wastes me weeks to figure out. Could you share the dataset with me and I can download it from my laptop which can access any website. I promise I will use it followed academic license. Thank you.

@zimingzhong Hi i'm also a researcher in china having the same problem, i wonder if it's possible for you to share your RealEstate10K dataset with me? Thank you!

**Comment by YLongJin** [comment]
@zimingzhong  @zifeiyuu I find the dataset on the huggingface, you could download with vpn in China .
https://huggingface.co/datasets/yangtaointernship/RealEstate10K-subset
